auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 3m
  chunk_retain_period: 1m

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h


compactor:
  working_directory: /loki/compactor
  shared_store: s3


storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: s3

  aws:
    s3: s3://DUMMY_MINIO_ACCESS_KEY:DUMMY__MINIO_SECRET_KEY@minio:9000/loki
    endpoint: minio:9000
    insecure: true

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_line_size: 256000
  # Control cardinality
  max_streams_per_user: 15000
  max_global_streams_per_user: 10000
  # lable limits 
  max_label_name_length: 1024
  max_label_value_length: 4096
  max_label_names_per_series: 30
